// apps/web/components/option/option.tsx
import type { IOptionColorName, IOptionColorShade } from '@egodb/core'
import type { PolymorphicComponentProps, BadgeProps } from '@egodb/ui'
import { Badge } from '@egodb/ui'

interface IProps extends PolymorphicComponentProps<'span', BadgeProps> {
  id: string
  colorName: IOptionColorName
  shade: IOptionColorShade
  name: string
}

export const Option: React.FC<IProps> = ({ colorName, name, shade, id, ...rest }) => {
  return (
    <Badge<'span'> {...rest} radius="xs" color={`${colorName}.${shade}`} data-option-id={id}>
      {name}
    </Badge>
  )
}

// apps/frontend-next/src/lib/option/Option.svelte
<script lang="ts">
	import type { Option } from '@undb/core'
	import cx from 'classnames'
	import { Badge } from 'flowbite-svelte'

	export let option: Option

	const textColor = option.color.shade > 5 ? '!text-dark' : '!text-white'
</script>

<Badge class={cx(`bg-${option.color.name}-${option.color.shade * 100}`, textColor)}>
	{option.name.value}
</Badge>
