// apps/frontend-next/src/lib/option/Option.svelte
<script lang="ts">
	import type { Option } from '@undb/core'
	import cx from 'classnames'
	import { Badge } from 'flowbite-svelte'

	export let option: Option

	const textColor = option.color.shade > 5 ? '!text-dark' : '!text-white'
</script>

<Badge class={cx(`bg-${option.color.name}-${option.color.shade * 100}`, textColor)}>
	{option.name.value}
</Badge>

// apps/frontend/src/features/option/option.tsx
import type { IOptionColorName, IOptionColorShade } from '@undb/core'
import type { BadgeProps } from '@undb/ui'
import { Badge } from '@undb/ui'

interface IProps {
  colorName: IOptionColorName
  shade: IOptionColorShade
  name: string
}

export const Option: React.FC<IProps> = ({ colorName, name, shade, ...rest }) => {
  const color = `${colorName}.${shade}`
  const variant: BadgeProps['variant'] = shade < 5 ? 'light' : 'filled'
  return (
    <Badge<'span'>
      component="span"
      {...rest}
      radius="xs"
      bg={color}
      variant={variant}
      styles={{
        root: {
          textTransform: 'unset',
        },
      }}
    >
      {name}
    </Badge>
  )
}
